import type {Metadata} from "next";
import {Montserrat} from "next/font/google";
import "./globals.css";
import {NextRequest} from "next/server";
import Navbar from "./components/Navbar/Navbar";
import {getUser} from "@/https/get";
import {cookies} from "next/headers";

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({children}: {children: React.ReactNode}) => {
  const {user} = await getUser(cookies);
  const userId: string | undefined = user && user?.user?.id;

  console.log("what is user", user);
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} max-w-[500px] md:max-w-[760px] largeLaptops:max-w-[980px] xlDisplay:max-w-[1200px] w-[100%] m-auto bg-green-300 from-green-400 to-yellow-800`}
        suppressHydrationWarning={true}
      >
        <Navbar
          user={userId}
          profile_url={user.user?.user_metadata.avatar_url}
          full_name={user.user?.user_metadata.full_name}
          email={user.user?.user_metadata.email}
        />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
