import type {Metadata} from "next";
import {Montserrat} from "next/font/google";
import "./globals.css";
import {NextRequest} from "next/server";
import Navbar from "./components/Navbar/Navbar";
import {getUser} from "@/https/get";
import {cookies} from "next/headers";

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({children}: {children: React.ReactNode}) => {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} min-h-screen w-[100%] m-auto bg-green-300 from-green-400 to-yellow-800`}
        // className={`${montserrat.className} min-h-screen max-w-[400px] md:max-w-[760px] largeLaptops:max-w-[980px] xlDisplay:max-w-[1200px] w-[100%] m-auto bg-green-300 from-green-400 to-yellow-800`}
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
